###############################
# FICHIER /.run/config/Brewfile
###############################

# HTTP client (used to fetch Homebrew, module descriptors and module archives)
brew "curl"

# Cross-platform GNU utilities (required for Linux compatibility)
brew "coreutils"

# Yaml processor (used to parse tools.yaml files, module descriptors and config.yaml file)
brew "yq"

# JSON processor (required for "yq")
brew "jq"

