###############################
# FICHIER /.run/config/config.yaml
###############################

# Managed by update module: /.run/core/update
update_settings:
  initialized: false
  auto_update: false
  last_update:
  freq_days:
  next_update:

