# Uncomment and run :
# docker build -f /Users/gui/Repos/gacli/gacli/tests/docker/dockerfiles/Dockerfile.vbatts/slackware-sudo -t vbatts/slackware-sudo /Users/gui/Repos/gacli/gacli/tests/docker/context
# docker run -it --rm -v /Users/gui/Repos/gacli/gacli/tests/docker/shared:/shared vbatts/slackware-sudo

FROM vbatts/slackware

# Add sudo
RUN slackpkg update && \
    echo "sudo: ALL=(ALL) ALL" >> /etc/sudoers && \
    yes | slackpkg install sudo
