# Uncomment and run :
# docker build -f /Users/gui/Repos/gacli/gacli/tests/docker/dockerfiles/Dockerfile.archlinux-sudo -t archlinux-sudo /Users/gui/Repos/gacli/gacli/tests/docker/context
# docker run -it --rm -v /Users/gui/Repos/gacli/gacli/tests/docker/shared:/shared archlinux-sudo

FROM archlinux

# Add sudo
RUN pacman -Sy --noconfirm sudo
