# ────────────────────────────────────────────────────────────────
# Config
# ────────────────────────────────────────────────────────────────

update:
  - last_update = 2025-02-01
  - auto_update = true
  - freq_days = 7
  - next_update = 2025-02-07

# ────────────────────────────────────────────────────────────────
# Your custom tools
# ────────────────────────────────────────────────────────────────

# 1. Add or remove any formula, cask or module in this file
# 2. Save the file
# 3. Run "gacli update" command:
  # → GACLI will automatically download and install missing formulae, casks and modules
  # → GACLI will automatically update all installed formulae, casks and modules
  # → You can immediatly use commands exposed by the newly added modules

formulae:
  # List your custom HOMEBREW FORMULAE here or run `gacli add-formula <formula_name>` / `gacli rm-formula <formula_name>`
  - "gh"                      # ---> TODO: create a module "dev_tools"
  - "pyenv"                   # ---> TODO: create a module "ai_tools"
casks:
  # List your custom HOMEBREW CASKS here or run `gacli add-cask <cask_name>` / `gacli rm-cask <cask_name>`
  - "visual-studio-code"      # ---> TODO: add to module "dev_tools"
  - "ollama"                  # ---> TODO: add to module "ai_tools"
  - "stats"                   # ---> TODO: create a module "monitoring"
  - "maccy"                   # ---> TODO: create a module "qol"
modules:
  # List your custom GACLI MODULES here or run `gacli add <module_name>` / `gacli rm-cask <cask_name>`
