FROM archlinux

RUN pacman -Sy --noconfirm sudo wget

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

# CMD ["sh", "-c", "wget -q https://raw.githubusercontent.com/guillaumeast/gacli/refs/heads/dev/installer/http/install.sh -O /tmp/install.sh && sh /tmp/install.sh"]
CMD ["sh", "-c", "wget -qO- https://raw.githubusercontent.com/guillaumeast/gacli/refs/heads/dev/installer/http/install.sh | sh"]
