FROM mageia

# Add sudo
RUN urpmi.update -a && \
    urpmi --auto sudo wget && \
    urpme --auto-orphans

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD [ "sh" ]

