FROM opensuse/leap

# Add sudo
RUN zypper refresh && \
    zypper install -y sudo wget

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD ["sh", "-c", "wget -qO- https://raw.githubusercontent.com/guillaumeast/gacli/refs/heads/dev/installer/http/install.sh | sh"]
