#############################################
# From: /Users/gui/Repos/gacli/Brewfile
#############################################
# Organize your dependencies by creating your own custom modules
# See: https://github.com/guillaumeast/gacli/blob/master/README.md (TODO: why 'blob' ???)

# Or just add your custom dependencies above here as:
# brew "formula_name"
# cask "cask_name"




##################################################
# TODO: delete all from here to let it clean for user.
# TODO: bundle the above tools in custom modules with their own Brewfile
# OBJECTIF: make clear which tool is needed for what
# Bundle all listed modules into a meta-module gacli/modules/user_modules/my_setup (would it work ??)

##################################################
# ---> gacli/modules/user_modules/dev_tools

# IDE
cask "visual-studio-code"

# Versionning
brew "git"

# Hosting
brew "gh"

##################################################
# ---> gacli/modules/user_modules/ai_tools

# Python version manager
brew "pyenv"

# Local LLM engine
cask "ollama"

##################################################
# ---> gacli/modules/user_modules/monitoring

# Hardware monitor (macOS)
cask "stats"

##################################################
# ---> gacli/modules/user_modules/qol

# Clipboard manager (macOS)
cask "maccy"


#############################################
# From: /Users/gui/Repos/gacli/modules/.launcher/Brewfile
#############################################
# GACLI required dependencies (NEVER REMOVE THOSE!)

# Cross-platform tools
brew "coreutils"

# Json processor
brew "jq"

# Versionning
brew "git"


#############################################
# From: /Users/gui/Repos/gacli/modules/user_modules/llm_compiler/Brewfile
#############################################
# llm_compiler module dependencies

# Directory structure visualizer
brew "tree"

# Universal document converter
brew "pandoc"
