#!/usr/bin/env zsh
###############################
# FICHIER /tests/_support/bootstrap.zsh
###############################

[[ ! -d "./.git" ]] && echo "\033[31mError: Please run tests from repo root folder\033[0m"

export DIR_ROOT="${PWD}"
export DIR_SRC="${DIR_ROOT}/src"
export DIR_TESTS="${DIR_ROOT}/tests"
export DIR_FIXTURE="${DIR_TESTS}/fixture"
