FROM opensuse/leap

# Add sudo
RUN zypper refresh && \
    zypper install -y sudo

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD [ "sh", "/shared/install.sh" ]
