# Uncomment and run :
# docker build -f /Users/gui/Repos/gacli/gacli/tests/docker/dockerfiles/Dockerfile.gentoo/stage3-sudo -t gentoo/stage3-sudo /Users/gui/Repos/gacli/gacli/tests/docker/context
# docker run -it --rm -v /Users/gui/Repos/gacli/gacli/tests/docker/shared:/shared gentoo/stage3-sudo

FROM gentoo/stage3

# Add sudo
RUN emerge --sync && \
    emerge --quiet sudo

# Switch to non-root user
RUN useradd -m -s /bin/sh appuser
USER appuser
WORKDIR /home/appuser

# Run installer and return exit code
CMD [ "sh", "/shared/install.sh" ]
