# Uncomment and run :
# docker build -f /Users/gui/Repos/gacli/gacli/tests/docker/dockerfiles/Dockerfile.mageia-sudo -t mageia-sudo /Users/gui/Repos/gacli/gacli/tests/docker/context
# docker run -it --rm -v /Users/gui/Repos/gacli/gacli/tests/docker/shared:/shared mageia-sudo

FROM mageia

# Add sudo
RUN urpmi.update -a && \
    urpmi --auto sudo && \
    urpme --auto-orphans

# Switch to non-root user
RUN useradd -m -s /bin/sh appuser
USER appuser
WORKDIR /home/appuser

# Run installer and return exit code
CMD [ "sh", "/shared/install.sh" ]
