# Uncomment and run :
# docker build -f /Users/gui/Repos/gacli/gacli/tests/docker/dockerfiles/Dockerfile.fedora-sudo -t fedora-sudo /Users/gui/Repos/gacli/gacli/tests/docker/context
# docker run -it --rm -v /Users/gui/Repos/gacli/gacli/tests/docker/shared:/shared fedora-sudo

FROM fedora

# Add sudo
RUN dnf install -y sudo && \
    dnf clean all

# Switch to non-root user
RUN useradd -m -s /bin/sh appuser
USER appuser
WORKDIR /home/appuser

# Run installer and return exit code
CMD [ "sh", "/shared/install.sh" ]
