###############################
# FICHIER /.data/config/update.config.yaml
###############################

# [Auto-update config descriptor]
   #   - Stores update status and timestamps
   #   - Defines update frequency and toggle
   #   - Used for auto-update scheduling

   # Depends on:
   #   - (none)             → pure data file

   # Used by:
   #   - update.zsh         → loads and saves update settings via `parser.zsh`

   # Note: All read/write operations are delegated to parser.zsh
#

initialized: false
auto_update: false
last_update:
freq_days:
next_update:

