FROM fedora

# Add sudo
RUN dnf install -y sudo git && \
    dnf clean all

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD [ "sh" ]

