FROM debian

# Add sudo
RUN apt-get update && \
    apt-get install -y sudo curl && \
    apt-get clean

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD ["sh", "-c", "curl -fsSL https://raw.githubusercontent.com/guillaumeast/gacli/refs/heads/dev/installer/http/install.sh | sh"]
