FROM mageia

# Add sudo
RUN urpmi.update -a && \
    urpmi --auto sudo curl && \
    urpme --auto-orphans

RUN groupadd -f sudo
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" | EDITOR='tee -a' visudo

RUN useradd -m -s /bin/sh appuser -G sudo
USER appuser
WORKDIR /home/appuser

CMD ["sh", "-c", "curl -fsSL https://raw.githubusercontent.com/guillaumeast/gacli/refs/heads/dev/installer/http/install.sh -o /tmp/install.sh && sh /tmp/install.sh"]
