###############################
# FICHIER /installer/Brewfile
###############################

brew "coreutils"    # CROSS-PLATFORM TOOLS → Required to run GACLI on macOS and Linux
brew "jq"           # JSON PARSER → Required by "yq"

