###############################
# FICHIER /installer/Brewfile
###############################

brew "curl"         # HTTP CLIENT → Required to donwload Homebrew and GACLI files
brew "bash"         # SHELL INTERPRETER → Required to run Homebrew
brew "zsh"          # SHELL INTERPRETER → Required to run GACLI
brew "coreutils"    # CROSS-PLATFORM TOOLS → Required to run GACLI on macOS and Linux
brew "jq"           # JSON PARSER → Required by "yq"

